### ISSUE TITLE
Check dependencies defined in pyproject.toml

### ISSUE THREAD

**Issue by justinmayer** [Lucas-C/pre-commit-hooks-safety#11]
Hi Lucas! Many thanks for creating this very helpful tool. With more and more projects defining dependencies in `pyproject.toml` (e.g., via Poetry), would you consider adding support for checking dependencies defined in that file? I imagine an initial implementation could support [Poetry](https://python-poetry.org/) by checking `pyproject.toml` for the presence of `[tool.poetry.dependencies]` and/or `[tool.poetry.dev-dependencies]` keys, and if one or both of those keys are present, using Poetry's [export-to-requirements.txt feature](https://python-poetry.org/docs/cli/#export) and running the equivalent of:
```
poetry export --dev --format requirements.txt | safety check --stdin
```

What do you think?

**Comment by Lucas-C** [comment]
Good idea!

This is now implemented in `v1.2.0`: https://github.com/Lucas-C/pre-commit-hooks-safety/releases

**Comment by justinmayer** [comment]
Many thanks for implementing this so quickly, Lucas! 👏 

Using the following configuration stanza…
```
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.0
    hooks:
      - id: python-safety-dependencies-check
```

… I used Pre-commit 2.10.0 in the root of the https://github.com/justinmayer/kagi repository and got the following error:
```
(kagi) ~/P/kagi ➤ pre-commit run -v --all-files python-safety-dependencies-check
safety...................................................................Failed
- hook id: python-safety-dependencies-check
- duration: 0.4s
- exit code: 2

usage: safety_check
       [-h]
       [--full-report]
       [--short-report]
       [--ignore IGNORE]
       files
       [files ...]
safety_check: error: Unsupported build tool: this pre-commit hook currently only handles pyproject.toml with Poetry
```
As you can see, the [`pyproject.toml`](https://github.com/justinmayer/kagi/blob/master/pyproject.toml#L1) file contains `[tool.poetry]`, so I'm not sure why this error occurs. Do you have any ideas?

**Comment by Lucas-C** [comment]
Please try `v1.2.1`!
I just tested it with your repo and it works fine :)

**Comment by justinmayer** [comment]
That seems to have fixed the issue. Thanks again for the velocity — impressive response time! 😁
