### ISSUE TITLE
Outputs a Warning from poetry.

### ISSUE THREAD

**Issue by MarximusMaximus** [Lucas-C/pre-commit-hooks-safety#37]
When running preicommit-hooks-safety, the following warning is output:
```
The `--dev` option is deprecated, use the `--with dev` notation instead.
```
The warning is coming from poetry.

**Comment by Lucas-C** [comment]
I solved this in https://github.com/Lucas-C/pre-commit-hooks-safety/commit/b4569046acc0b4a00aa5a77a3b2240fa5345b2d2
but this bug in poetry prevents this to work correctly: https://github.com/python-poetry/poetry-plugin-export/issues/173

I'm going to wait for a resolution on their side before making any new release

**Comment by Lucas-C** [comment]
Another issue with Pylint prevents the GitHub Actions pipeline to pass: https://github.com/PyCQA/pylint/issues/7972

**Comment by Lucas-C** [comment]
The final issues were solved by https://github.com/Lucas-C/pre-commit-hooks-safety/commit/fbb7a8336f32b5fc39d23bf93e2f2d6becd2eac5
