### ISSUE TITLE
Fails with older poetry versions: NoSuchOptionException: The "--with" option does not exist.

### ISSUE THREAD

**Issue by yrro** [Lucas-C/pre-commit-hooks-safety#40]
The `convert_poetry_to_requrements` function fails when Poetry 1.1.14 is installed. This version doesn't accept the `--with` `dev` option.

This older version of Poetry uses the `--dev` option, which is still accepted by current Poetry versions. So changing `convert_poetry_to_requrements` to use `--dev` would allow it to work on older & current Poetry versions.

**Comment by Lucas-C** [comment]
Hi @yrro and thank you for reporting this issues.

Actually we made that change recently to support recent versions of poetry: https://github.com/Lucas-C/pre-commit-hooks-safety/commit/b4569046acc0b4a00aa5a77a3b2240fa5345b2d2
I am not  fully confident in my memory, but I thought using `--dev` made the unit tests fail with a recent version of Poetry.

I would welcome a solution that passes `--dev` for older versions of Poetry, and `--with dev` for recent versions.
Would you like to submit a PR implementing this?
Do you have other suggestions?

**Comment by yrro** [comment]
If `--dev` isn't working on current Poetry then I think it's not worth adding logic to make the command line conditional on the Poetry version. Most people are probably on a pretty up-to-date version anyway...
