### ISSUE TITLE
Hook fails because there are no dev dependency group in our poetry config

### ISSUE THREAD

**Issue by nils-van-zuijlen** [Lucas-C/pre-commit-hooks-safety#44]
We have chosen to split our dependencies more than just a main and a dev group, so now we do not have a dev group at all.
Instead we have `main`, `docs`, `lint`, `tools` and `test`.

In Poetry 1.5.0, this now breaks because https://github.com/python-poetry/poetry/pull/7529 was merged and unknown group names now trigger an error in poetry when used with `--only`, `--with` and `--without`.

Would it be possible to have the full list of optional groups be taken as an argument? This would also help with #41

**Comment by Lucas-C** [comment]
> Would it be possible to have the full list of optional groups be taken as an argument? This would also help with #41

That seems like a nice addition to me, so yes! 😊

Would you like to submit a PR to implement this?
