### ISSUE TITLE
`binsafety_check`causing max recursion failure

### ISSUE THREAD

**Issue by zilerehman** [Lucas-C/pre-commit-hooks-safety#6]
```
File "/home/jenkins/workspace/cl-infratools-jenkinsfile_v1.1.1/.cache/pre-commit/repoLdwXZS/y_env-python2.7/binsafety_check", line 8, in <module>

RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Lucas-C** [comment]
Hi

Could you please describe a bit more your issue / how to reproduce it ?

And especially : why do you think your issue has something to do with this hook ?
`binsafety_check` does not ring a bell to me

**Comment by zilerehman** [comment]
Thanks I will double check and open up a new bug if it's related to the prehook lib. Will close it for now.
