### ISSUE TITLE
support `--ignore=x,y,z` ignore in `args: [`

### ISSUE THREAD

**Issue by graingert** [Lucas-C/pre-commit-hooks-safety#9]
re-opening https://github.com/Lucas-C/pre-commit-hooks-safety/issues/7

**Comment by Lucas-C** [comment]
As mentioned in #7, this is already supported and tested:
https://github.com/Lucas-C/pre-commit-hooks-safety/blob/master/tests/safety_test.py#L21

I'm going to close this unless you detail how you have a specific distinct need.

**Comment by graingert** [comment]
this is missing support for `--ignore=x,y,z`

**Comment by Lucas-C** [comment]
Admittedly, but `--ignore=x --ignore=y --ignore=z` is supported.
As it is the "canonical" syntax of `safety check` options, it seems best to me to conform to it.
Don't you think that, by having an alternative / replacement syntax like `--ignore=x,y,z`, it would bring more confusion than usability ?
